security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_api:
            pattern: ^/api
            stateless: true
            json_login:
                check_path: /api/login_check
                username_path: email 
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure

        main:
            lazy: true
            provider: app_user_provider
            # HTML form login (pour /login)
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                csrf_token_id: authenticate
                username_parameter: email
                password_parameter: password
            logout:
                path: app_logout
                target: app_login

    access_control:
        # Public API
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }

        # Authenticated API
#- { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

        # Frontend routes
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }

        # Admin routes
        - { path: ^/admin, roles: ROLE_ADMIN }

        # Utilisateur connecté
        - { path: ^/profile, roles: ROLE_USER }